# Generated by Django 6.0.1 on 2026-01-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Муниципалитет')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='settlements.region')),
            ],
            options={
                'verbose_name': 'Муниципалитет',
                'verbose_name_plural': 'Муниципалитеты',
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Населенный пункт')),
                ('type', models.CharField(max_length=50, verbose_name='Тип НП')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Население')),
                ('children_population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дети')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='settlements.municipality')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
    ]
