# Generated by Django 6.0.1 on 2026-01-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='children_population',
        ),
    ]
